In [23]:
## Aplicando funções personalizadas no Pandas

### Usando método .apply

In [24]:
# Importando bibliotécas

import pandas as pd

In [ ]:
# apply

df = pd.read_csv("../data/clientes.csv")

# Aplicando função personalizada na coluna 'idCliente'

def get_lst_id(x): # Declarando função que recebe um valor da 'idCliente' e separa mantendo última parte
    return x.split('-')[-1]

# Aplicando função na coluna

df['IdNovo'] = df['idCliente'].apply(get_lst_id)

df.head()

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,dtCriacao,dtAtualizacao,IdNovo
0,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,686,NaN,NaN,47f581ec52a1
1,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,NaN,NaN,f9fbba90f530
2,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,NaN,NaN,fc911ea28a92
3,0033b737-8235-4c0f-9801-dc4ca185af00,0,1,0,0,0,1090,0000-00-00 00:00:00.000,2025-02-19 12:48:24.632,dc4ca185af00
4,00684343-40b5-4ce7-b2e8-71a5340973bf,0,0,0,0,0,0,NaN,NaN,71a5340973bf

In [ ]:
uf = pd.read_csv("../Módulo_02/UFs_Brasil.csv", sep=";")

# Aplicando função personalizada em varias colunas

def str_to_float(x:str): # Declarando função que trata str e transforma em float
    x = float(x.replace(" ","")
               .replace(",", ".")
               .replace("\xa0", ""))
    return x

colunas = ['Área (km²)', 'População (Censo 2022)', 'PIB (2015)', 'PIB per capita (R$) (2015)']

# Aplicando função com for

for i in colunas:
    uf[i] = uf[i].apply(str_to_float)

uf.dtypes

Unnamed: 0                       int64
Bandeira                       float64
Unidade federativa              object
Abreviação                      object
Sede de governo                 object
Área (km²)                     float64
População (Censo 2022)         float64
Densidade (2005)                 int64
PIB (2015)                     float64
(% total) (2015)                 int64
PIB per capita (R$) (2015)     float64
IDH (2010)                       int64
Alfabetização (2016)            object
Mortalidade infantil (2016)     object
Expectativa de vida (2016)      object
dtype: object

In [32]:
# Aplicando função para criação de uma coluna a partir de valores de outra

def uf_to_regiao(uf): # Declarando função que avalia estado e retorna região

    if uf in ["Distrito Federal", "Goiás", "Mato Grosso", "Mato Grosso do Sul"]:
        return "Centro-Oeste"
    elif uf in ["Alagoas","Bahia", "Ceará", "Maranhão", "Paraíba", "Pernambuco", "Piauí", "Rio Grande do Norte", "Sergipe"]:
        return "Nordeste"
    elif uf in ["Acre", "Amapá", "Amazonas", "Pará", "Rondônia", "Roraima", "Tocantins"]:
       return "Norte"
    elif uf in ["Espírito Santo","Minas Gerais", "Rio de Janeiro", "São Paulo"]:
        return "Sudeste"
    elif uf in ["Paraná", "Rio Grande do Sul", "Santa Catarina"]:
        return "Sul"
    
# Aplicando função na coluna e atraibuindo em nova coluna

uf["Região"] = uf["Unidade federativa"].apply(uf_to_regiao)

uf.head()

,Unnamed: 0,Bandeira,Unidade federativa,Abreviação,Sede de governo,Área (km²),População (Censo 2022),Densidade (2005),PIB (2015),(% total) (2015),PIB per capita (R$) (2015),IDH (2010),Alfabetização (2016),Mortalidade infantil (2016),Expectativa de vida (2016),Região
0,0,NaN,Acre,AC,Rio Branco,164122.2,830018.0,430,13622000.0,2,16953.46,663,"86,9%","17,0‰","73,9 anos",Norte
1,1,NaN,Alagoas,AL,Maceió,27767.7,3127683.0,10861,46364000.0,8,13877.53,631,"80,6%","19,5‰","71,6 anos",Nordeste
2,2,NaN,Amapá,AP,Macapá,142814.6,733759.0,416,13861000.0,2,18079.54,708,95%,"23,2‰","73,9 anos",Norte
3,3,NaN,Amazonas,AM,Manaus,1570745.7,3941613.0,205,86560000.0,14,21978.95,674,"93,1%","18,2‰","71,9 anos",Norte
4,4,NaN,Bahia,BA,Salvador,564692.7,14141626.0,2446,245025000.0,41,16115.89,660,87%,"17,3‰","73,5 anos",Nordeste

In [33]:
# Aplicando função personalizada em linhas

def pib_per_capita_manual(x): # Declarando função que calcula a partir de duas colunas
    return x['PIB (2015)'] / x['População (Censo 2022)']

# Aplicando função com argumento axis=1 para aplicação linha a linha

uf['PIB per capita manual'] = uf.apply(pib_per_capita_manual, axis=1)

uf.head()

,Unnamed: 0,Bandeira,Unidade federativa,Abreviação,Sede de governo,Área (km²),População (Censo 2022),Densidade (2005),PIB (2015),(% total) (2015),PIB per capita (R$) (2015),IDH (2010),Alfabetização (2016),Mortalidade infantil (2016),Expectativa de vida (2016),Região,PIB per capita manual
0,0,NaN,Acre,AC,Rio Branco,164122.2,830018.0,430,13622000.0,2,16953.46,663,"86,9%","17,0‰","73,9 anos",Norte,16.411692
1,1,NaN,Alagoas,AL,Maceió,27767.7,3127683.0,10861,46364000.0,8,13877.53,631,"80,6%","19,5‰","71,6 anos",Nordeste,14.823753
2,2,NaN,Amapá,AP,Macapá,142814.6,733759.0,416,13861000.0,2,18079.54,708,95%,"23,2‰","73,9 anos",Norte,18.890399
3,3,NaN,Amazonas,AM,Manaus,1570745.7,3941613.0,205,86560000.0,14,21978.95,674,"93,1%","18,2‰","71,9 anos",Norte,21.960553
4,4,NaN,Bahia,BA,Salvador,564692.7,14141626.0,2446,245025000.0,41,16115.89,660,87%,"17,3‰","73,5 anos",Nordeste,17.326508